spring.profiles.active=prod

server.port=8084

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

logging.file.name=logs/library-app.log
logging.level.com.epam.rd.autocode=INFO